apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-cloud-alibaba
  namespace: kube-ops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-cloud-alibaba
  template:
    metadata:
      labels:
        app: spring-cloud-alibaba
    spec:
      containers:
        - name: spring-cloud-alibaba
          image: $image
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: spring-cloud-alibaba
  namespace: kube-ops
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: spring-cloud-alibaba
      nodePort: 30008
  selector:
    app: spring-cloud-alibaba
  type: NodePort