server:
  port: 8080
spring:
  cloud:
    sentinel:
      transport:
        dashboard: sentinel:8080
      eager: true #服务注启动，直接注册到dashboard
      datasource:
        ds:
          nacos:
            server-addr: nacos-headless:8848
            dataId: ${spring.application.name}-sentinel
            groupId: DEFAULT_GROUP #nacos中存储规则的groupId
            rule-type: flow #定义存储的规则类型,该参数是spring cloud alibaba升级到0.2.2之后增加的配置

  application:
    name:  spring-cloud-alibaba




